# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 604432e447ef4c71a63c6c59c856821c71f622cc4a2ab183167ad88391c6043d28d41f92ab950487682798d710df6fb717318f5d2b829c1df6ce9d34bb0a0953

test:
  secret_key_base: 80919d26e704ae8fadb83fdc0cf8a781f505e1116f66b7884c8fad21f361d2de3a671d2ddf10a732ecf8b11ec6e198423f994a7a424fc842b8d50231993e2583

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
